name: "Bug Report"
description: "Report a bug in MassOS"
title: "[Bug]: "
labels: "bug"
body:
- type: "checkboxes"
  attributes:
    label: "Checklist"
    description: "Please make sure you have read the following:"
    options:
      - label: "I have searched for [other issues](https://www.github.com/MassOS-Linux/MassOS/issues), and can confirm my issue has not already been reported."
        required: true
      - label: "If this is an issue with a specific program, I have checked the upstream project's issue tracker and determined that it is an issue with MassOS itself."
        required: true
      - label: "If this is a hardware-related issue, I have made sure it exists on the standard ISO and is not exclusive to the ISO which doesn't include firmware."
        required: true
- type: "input"
  attributes:
    label: "MassOS version"
    description: "What version of MassOS are you using? Run `massos-release` in a terminal if unsure."
    placeholder: "2022.10"
  validations:
    required: true
- type: "input"
  attributes:
    label: "Kernel version"
    description: "What is the output of `uname -srvm`?"
    placeholder: "Linux 6.0.0-massos #1 SMP PREEMPT_DYNAMIC Tue Oct 4 23:50:51 UTC 2022 x86_64"
  validations:
    required: false
- type: "checkboxes"
  attributes:
    label: "Subject"
    description: "Which of the following best describes your issue (multiple responses are OK)?"
    options:
      - label: "Issue with the MassOS Live CD and/or installing MassOS."
      - label: "Issue with a particular piece of software in MassOS."
      - label: "Issue with booting or startup of MassOS."
      - label: "Issue with hardware or peripherals on MassOS."
      - label: "Issue with the MassOS documentation."
      - label: "Issue with compiling MassOS from source."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Expected Behavior"
    description: "A clear description of what you expected to happen."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Actual Behavior"
    description: "A clear description of what actually happened."
  validations:
    required: true
- type: "textarea"
  attributes:
    label: "Steps to reproduce"
    description: "A clear description of how to reproduce the problem."
    placeholder: "Open `...`, click on `...`, select `...`, see error."
  validations:
    required: false
- type: "textarea"
  attributes:
    label: "Additional Information"
    description: "Any additional information you feel will be useful for debugging/solving your issue."
  validations:
    required: false
